spring.application.name=RetrievalAugmentedGeneration

# Groq API (OpenAI-compatible)
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-120b
spring.ai.openai.api-key=${GROQ_API_KEY}

spring.ai.model.chat=openai
spring.ai.model.embedding=ollama

# Embeddings (ollama)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text

# Vector Store (pgvector)
spring.ai.vectorstore.pgvector.table-name=chunks
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# Server
server.port=8080

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/rag_database
spring.datasource.username=rag_user
spring.datasource.password=${pg_db_password}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
